name: sbom
on:
  push:
    branches:
    - main
    
permissions:
  contents: write

jobs:
  scan:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Trivy SBOM
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependecy-results.sbom.json'
          scan-ref: .
          github-pat: ${{ secrets.GITHUB_TOKEN }}
