name: simple-scan
on:
  push:
    branches:
    - main

jobs:
  scan:
    name: simple-scan
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: action/checkout@v4

    - name: Trivy scan
      uses: aquasecurity/trivy-action@0.23.0
      with:
        scan-type: 'fs'
        scan-ref: .
